abbr l 'ls -la'
abbr la 'ls -a'
abbr ll 'ls -l'
abbr aptup 'sudo aptitude update && sudo aptitude full-upgrade'
abbr sizeof 'du -sh'
abbr x11vncUnencrypted  'x11vnc -auth guess -forever -loop -noxdamage -repeat -rfbauth /home/simon/.vnc/passwd -rfbport 5900 -shared'