#!/bin/bash
#
WP=$1


if command -v "feh" >/dev/null 2>&1; then
        feh --bg-fill "$WP" 2> /dev/null
elif command -v "nitrogen" >/dev/null 2>&1; then
        nitrogen --set-zoom-fill --save "$WP" 2> /dev/null
fi

if [[ -n $SWAYSOCK ]]; then
    swaymsg output "*" bg "$WP" fill 2> /dev/null
fi

exit 0
